name: postgresql
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/postgresql/data
    ports:
      - "${PORT:-5432}:5432"
    restart: unless-stopped
    networks:
      - database

networks:
  database:
    external: true
