services:
  grafana:
    image: grafana/grafana:12.0.2-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    user: "${UID}:${GID}"
    volumes:
      - ${DB_DATA_LOCATION}:/var/lib/grafana
    restart: unless-stopped