name: redis
services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes --requirepass ${DB_PASSWORD}
    volumes:
      - ${DB_DATA_LOCATION}:/data
    ports:
      - "${PORT:-6379}:6379"
    restart: unless-stopped
    networks:
      - database

networks:
  database:
    external: true
